name: Static Page - Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.dgf_ssh_host }}
        username: ${{ secrets.dgf_ssh_user }}
        password: ${{ secrets.dgf_ssh_password }}
        port: 22
        source: "static_page"
        target: "httpdocs"
        strip_components: 1
        
